name: rider_frontend
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.1.0+4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.2.0
  firebase_auth: ^1.2.0
  firebase_database: ^7.0.0
  firebase_storage: ^8.1.0
  firebase_messaging: ^10.0.4
  firebase_analytics: ^8.2.0
  cloud_functions: ^1.1.0
  flutter_dotenv: ^3.1.0
  provider: ^4.3.3
  connectivity: ^3.0.4
  google_maps_flutter: ^2.0.6
  flutter_svg: ^0.22.0
  uuid: ^3.0.4
  image_picker: ^0.8.0+3
  permission_handler: ^8.0.1
  geolocator: ^7.2.0
  cupertino_icons: ^1.0.0
  http: ^0.13.0
  flutter_polyline_points: ^0.2.4
  encrypt: ^5.0.0
  pointycastle: ^3.1.3
  path_provider: ^2.0.2
  flutter_credit_card: ^2.0.0
  url_launcher: ^6.0.9
  system_settings: ^2.0.0
  image: ^3.0.2
  flutter_maps_place_picker:
    git:
      url: git@gitlab.com:arthur_abrantes/flutter_maps_place_picker.git
      ref: 6323602d551ce66bd18349832ef93f0827683c55

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.15.7
  mockito: ^5.0.12

flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/map_style.txt
    - .env

  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Light.ttf
          weight: 300
        - asset: fonts/OpenSans-Regular.ttf
        - asset: fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: fonts/OpenSans-Bold.ttf
