name: rider_frontend
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^3.1.0
  cupertino_icons: ^1.0.0
  google_fonts: ^1.1.2
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.0+1
  firebase_database: ^6.0.0
  firebase_storage: ^7.0.0
  image_picker: ^0.6.7+22
  provider: ^4.3.3
  http: ^0.12.2
  google_maps_flutter: ^1.2.0
  geolocator: ^6.2.1
  uuid: ^2.2.2
  permission_handler: 5.0.1+2
  flutter_polyline_points: ^0.2.4
  flutter_svg: ^0.19.3
  flutter_maps_place_picker:
    git:
      url: git@gitlab.com:arthur_abrantes/flutter_maps_place_picker.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.15.7
  mockito: ^4.1.4

flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/map_style.txt
    - assets/dev.env
    - assets/prod.env

  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Light.ttf
          weight: 300
        - asset: fonts/OpenSans-Regular.ttf
        - asset: fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: fonts/OpenSans-Bold.ttf
